global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "devhub-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8080"]

  - job_name: "postgres_exporter"
    static_configs:
      - targets: ["postgres_exporter:9187"]
